[programs.localnet]
mysolanaapp = "D3gXgvtPVAEzZCXc6SM8K5Btedhhf8BEeEEJjhkvCzGX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/eric/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
